[package]

name = "slog-envlogger"
version = "0.4.0"
authors = ["The Rust Project Developers", "Dawid Ciężarkiewicz <dpc@dpc.pw>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/dpc/slog-envlogger"
documentation = "https://github.com/dpc/slog-envlogger"
homepage = "https://github.com/dpc/slog-envlogger"
description = """
Port of de facto standard logger implementation for Rust, to `slog-rs` framework.
"""

[lib]
path = "src/lib.rs"

[dependencies]
slog = "1.0.0-alpha3"
regex = "0.1"
slog-term = "1.0.0-alpha3"
slog-stdlog = "1.0.0-alpha5"
log = "0.3.6"

[[test]]
name = "regexp_filter"
harness = false

