[package]

name = "slog-envlogger"
version = "2.0.0"
authors = ["The Rust Project Developers", "Dawid Ciężarkiewicz <dpc@dpc.pw>"]
license = "MIT/Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/slog-envlogger"
homepage = "https://github.com/slog-rs/slog"
repository = "https://github.com/slog-rs/envlogger"
description = """
Port of de facto standard logger implementation for Rust, to `slog-rs` framework.
"""

[lib]
path = "src/lib.rs"

[dependencies]
slog = "2"
regex = "0.1"
slog-term = "2"
slog-stdlog = "2"
slog-scope = "3"
slog-async = "2"
log = "0.3.6"

[[test]]
name = "regexp_filter"
harness = false

